/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.pepsoft.worldpainter;

import java.awt.image.BufferedImage;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.pepsoft.worldpainter.layers.Layer;

/**
 *
 * @author pepijn
 */
public class InfoPanel extends javax.swing.JPanel {
    /**
     * Creates new form InfoPanel
     */
    public InfoPanel() {
        initComponents();
    }

    public void setView(WorldPainter view) {
        this.view = view;
    }
    
    public void updateInfo(int x, int y) {
        // Update slope
        
        // Update layers
        Map<Layer, Integer> layerValues = view.getDimension().getLayersAt(x, y);
        if (layerValues != null) {
            for (Map.Entry<Layer, Integer> entry: layerValues.entrySet()) {
                Layer layer = entry.getKey();
                int value = entry.getValue();
                if (layerLabels.containsKey(layer)) {
                    BufferedImage icon = layer.getIcon();
                    JLabel label = new JLabel(layer.getName(), (icon != null) ? new ImageIcon(icon) : null, JLabel.LEADING);
                } else {
                    
                }
            }
        } else {
            if (! layerLabels.isEmpty()) {
                panelLayers.removeAll();
                layerLabels.clear();
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelLayers = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelSlope = new javax.swing.JLabel();

        jLabel1.setText("Slope:");

        jLabel2.setText("Layers:");

        panelLayers.setLayout(new java.awt.GridLayout(0, 1, 0, 2));

        jLabel3.setText("jLabel3");
        panelLayers.add(jLabel3);

        jLabel4.setText("jLabel4");
        panelLayers.add(jLabel4);

        labelSlope.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSlope))
                    .addComponent(jLabel2)
                    .addComponent(panelLayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelSlope))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelSlope;
    private javax.swing.JPanel panelLayers;
    // End of variables declaration//GEN-END:variables

    private WorldPainter view;
    private Map<Layer, JLabel> layerLabels = new HashMap<Layer, JLabel>();
}